<a href="https://colab.research.google.com/github/Franchertz/Python-Learning/blob/main/Numerical_Python(NumPy)_Part2ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numpy: Generating Random Values**

**with <np.random.rand>**

#Example: *Creating an array of a given shape and populating with random samples form a uniform distribution between 0 and 1*

In [ ]:
import numpy as np

In [ ]:
np.random.rand(3,2)

array([[0.36873788, 0.03643588],
       [0.5761742 , 0.67772736],
       [0.12800143, 0.34322226]])

In [ ]:
np.random.rand(5,3)

array([[0.20996734, 0.18291374, 0.69065458],
       [0.23476411, 0.84468728, 0.97579136],
       [0.493457  , 0.5374894 , 0.04893742],
       [0.28448251, 0.46257101, 0.23203518],
       [0.0572425 , 0.19900911, 0.59224405]])

**with <np.random.rand>**

In [ ]:
a = np.random.randn(3,3) #Returns sample from the "standard normal" distribution
a

array([[-0.5501054 ,  0.83530375, -0.3671542 ],
       [ 0.27087073,  0.69479907,  1.05792263],
       [-1.23820189,  0.61202913, -0.59685642]])

**with <np.random.randint>**

In [ ]:
#Generating 10 numbers between 4 and 15
mn=np.random.randint(4,15,10)
mn

array([14,  7,  9, 10,  9,  6, 11,  6,  4,  7])

In [ ]:
len(mn)

10

In [ ]:
mn.reshape(5,2)

array([[14,  7],
       [ 9, 10],
       [ 9,  6],
       [11,  6],
       [ 4,  7]])

In [ ]:
tt = np.random.randint(0,10, (4,3))
tt

array([[3, 0, 6],
       [6, 5, 2],
       [1, 2, 5],
       [4, 8, 4]])

#**Numpy Indexing & Slicing**

In [ ]:
mn=np.random.randint(4,15,10)
mn

array([11,  7, 13,  8, 10, 11,  8,  5,  7, 14])

In [ ]:
mn[1]

7

In [ ]:
mn[-1]

14

In [ ]:
mn[3:7]

array([ 8, 10, 11,  8])

In [ ]:
mn[3:]

array([ 8, 10, 11,  8,  5,  7, 14])

In [ ]:
mn[5:-2]

array([11,  8,  5])

In [ ]:
mn.resize(2,5)
mn

array([[11,  7, 13,  8, 10],
       [11,  8,  5,  7, 14]])

In [ ]:
mn.resize(5,2)
mn

array([[11,  7],
       [13,  8],
       [10, 11],
       [ 8,  5],
       [ 7, 14]])

In [ ]:
mn=np.arange(64)
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [ ]:
mn.resize(8,8)
mn

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
mn[2,3]

19

In [ ]:
mn[4,2:5]  #use : to select a range of rows or columns

array([34, 35, 36])

In [ ]:
mn[2:]

array([[16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63]])

In [ ]:
mn[3:,3:]

array([[27, 28, 29, 30, 31],
       [35, 36, 37, 38, 39],
       [43, 44, 45, 46, 47],
       [51, 52, 53, 54, 55],
       [59, 60, 61, 62, 63]])

In [ ]:
[mn > 25] #conditional indexing

[array([[False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False, False, False, False, False, False, False],
        [False, False,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True,  True,  True,  True]])]

In [ ]:
mn[mn >25]

array([26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42,
       43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
       60, 61, 62, 63])

#**Numpy Broadcasting**

In [ ]:
mn[mn > 25] = 25 #casting all the values that are greater than 25 to 25
mn

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [ ]:
mn[1:,4]

array([12, 20, 25, 25, 25, 25, 25])

#**Numpy: Creating a copy of a dataset**

In [ ]:
mn1=mn[3:,3:]
mn1

array([[25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25]])

In [ ]:
mn_copy=mn.copy()
mn_copy

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])

In [ ]:
mn_copy[mn_copy > 5] = 5  #Broadcasting all the numbers greater than 5 to 5
mn_copy

array([[0, 1, 2, 3, 4, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5]])

In [ ]:
mn #orignal data still intact

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25, 25]])