<a href="https://colab.research.google.com/github/Franchertz/Python-Learning/blob/main/Numerical_Python(NumPy)_Part1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Numerical Python**

It is used for numerical manipulation. 

It is used for N-dimensional array. It is the most preferred library in Python.

https://numpy.org/

In [ ]:
!pip install numpy  #First thing to do is install using the syntanx. if it is istalled you get the message below

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
import numpy as np  #then import numpy library.It is recommeded to ALIAS it for easy recall

In [ ]:
mylist = [1,2,3]
n = np.array(mylist)
n

array([1, 2, 3])

In [ ]:
type(mylist)

list

In [ ]:
type(n)

numpy.ndarray

In [ ]:
#mylist = [1,2,3]  # I could just include the list directly and get same results
n = np.array([1,2,3])
n

array([1, 2, 3])

#**Creating Multidimensional Numpy Arrays.**

In [ ]:
list_of_lists = np.array([[1,2,3],[4,5,6],[7,8,9]])
list_of_lists


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
list_of_lists.shape #use the shape method to find the dimension


(3, 3)

#**Numpy Arrange Function**

Returns evenly spaced values within a given interval

**Example**

Generating 10 numbers starting from 0, but the last digit will not appear

In [ ]:
np.arange(0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(10) #Python will read it as from 0 to 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(0,10,2) #Generate numbers from 0 to 10 at an interval of 2

array([0, 2, 4, 6, 8])

In [ ]:
for i in range(0,10):
  print(i)

0
1
2
3
4
5
6
7
8
9


In [ ]:
for i in range(0,10,3):
  print(i)

0
3
6
9


#**Numpy Zeros, Ones and Eye Functions**

In [ ]:
zero = np.zeros(50)
zero

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a = np.eye(10) #Shows an array ones in a diagonal 
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [ ]:
mn = np.arange(0,50)
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
len(mn)

50

#**Numpy Reshape Function**

In [ ]:
mn.reshape(5,10) #Specifying with rows(5) and columns(10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
mn

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [ ]:
new_variable=mn.reshape(5,10)
new_variable

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [ ]:
mn #Orignal value is still intact

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

#**Numpy Linspace**

In [ ]:
o = np.linspace(0,7,10)  #returns numbers from 0 to 7 and evenly spaced by 10
o

array([0.        , 0.77777778, 1.55555556, 2.33333333, 3.11111111,
       3.88888889, 4.66666667, 5.44444444, 6.22222222, 7.        ])

In [ ]:
len(o)

10

#**Numpy Resize Function**

In [ ]:
o.resize(5,2) #Resize alters data
o

array([[0.        , 0.77777778],
       [1.55555556, 2.33333333],
       [3.11111111, 3.88888889],
       [4.66666667, 5.44444444],
       [6.22222222, 7.        ]])

#**Numpy: Generating Random Values**

In [ ]:
np=random.rand(3,2)

NameError: ignored